id: PDE987A37
initial_creation_type: input
source_metadata:
  title: Pilgrimage Series
  language: bo
  description: 'Lotsawa House presents the following texts related to pilgrimage (gnas
    skor) and major sacred places (gnas):'
  volume:
    adb9afbfc8224c3e879bf211c9934609:
      title: The Three Types of Pilgrim
      parent: General
    f704784755dc4c92a83e5838beba0d2f:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Sacred Places
    d81687d189d64240a5eb03580a62806b:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Sacred Places
    eb5ff16a53ae4c048b1cdecba9775ca6:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Sacred Places
    dd31d51a6fa94d8aa03e4423a4471c68:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Sacred Places
    c992d64d5f8847c88ab322d24fdce74f:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Sacred Places
    60dd4e66cdcf4e2f98e08956f28ffbc5:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Sacred Places
    a6c1b9e84cfb4d4b8b2e85a8825129e1:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Sacred Places
    1186eb4640cf4f4eae6df44d52cc0b52:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    23d75319b1474f93a3c4a7d12f688387:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    d7aada3b6b45422783baa57fb3478da9:
      title: 'Gathering Auspiciousness: A Prayer of Aspiration Made in the Presence
        of the Sacred Mahābodhi Temple and its Imagery, Magadha, Land of the Āryas'
      parent: Sacred Places
    64510be579104bfa84e07a3fdc84607a:
      title: Guide to Sengchen Namdrak
      parent: Sacred Places
    bb74efdc1f924e83b79acb9ec25f557d:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    4e18a784ba4343e0bfdf1a312fb0c13e:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    7062b3207e2e4bcc9ad5da33dcbde834:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    9683e0d7323740a59847db6af2a01416:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    e7744dcd599d4d4aa48b822efd62ef60:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    264f74f0cb2e46f181a77c4df73a6879:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    21ac629db07d4f99a109fa6da0364041:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    299b85e9d8cb4e778d0e08c89c04656d:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Sacred Places
    71953386570447219f344cc6a3b204a5:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    8cc7b5fe1b004e538e036a695f6d3c1f:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    c29314aa56b34bd8b9a726112b0928c8:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    b58f7b71b3c34f77a4f8a80e0562f2aa:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Sacred Places
    79f962d587c741beb1c9b67ef6567c82:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Sacred Places
    63d48bdb1c0c4dd9a74cafd6601ceb89:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Sacred Places
    aa53f5e6a52b4b0a92560694a3fc31ed:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    d879773d20024879bc37f089235c790e:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: Sacred Places
    374b1bd2f6f84b128405f56ff2d4e85b:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    dc681e9527c34ad09115cf6b350caac3:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Sacred Places
    9b00f4ff648b474385fe84190639f7d1:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    1d4c4d6498cf4f5a9c28be5722ebd59f:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Sacred Places
    c7c57d3131c6479a904b97c5e2126799:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
created_at: '2022-03-01T05:06:14.969379'
last_modified_at: '2022-03-01T05:06:14.969382'
